project_id = "fbweiwckhlgblldqbhzy"

[auth]
enabled = true
external_email_enabled = true
external_anonymous_users_enabled = false
external_phone_enabled = false

[functions.create-razorpay-order]
verify_jwt = false

[functions.verify-razorpay-payment]
verify_jwt = false