// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbweiwckhlgblldqbhzy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZid2Vpd2NraGxnYmxsZHFiaHp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0Mjc2NzksImV4cCI6MjA2OTAwMzY3OX0.A9wjSE8L6Px2BISLB2r9i5GyaLwFyFfwdQio6qeDv8w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});